### ISSUE TITLE
thoth: TypeError: msecs must be a number

### ISSUE THREAD

**Issue by lloydde** [joyent/manta-thoth#120]
"thoth: TypeError: msecs must be a number" from all `thoth` commands I tried.

ENV
Mac 10.10.4 / homebrew
$ node --version
v0.12.7

I'll try under Node v0.10

**Comment by lloydde** [comment]
Confirmed, I don't see this symptom using node 0.10.

~~~
brew unlink node
brew install https://raw.githubusercontent.com/Homebrew/homebrew-versions/master/node010.rb
npm install -g npm@latest
npm install -g git://github.com/joyent/manta-thoth.git#master
~~~

**Comment by davepacheco** [comment]
I think this is node-manta#216, which is node-ssh-agent#5, which only happens on Node v0.12.
