### ISSUE TITLE
bump dependency versions and release 1.0.0

### ISSUE THREAD

**Issue by jclulow** [joyent/manta-thoth#144]
In order to allow building with newer versions of Node, and to provide for ECDSA SSH key support in the Manta client, we should bump the version of some of the dependencies we ship.

At the same time, we should release a version 1.0.0 to NPM.

**Comment by trentm** [comment]
https://cr.joyent.us/#/c/942

**Comment by trentm** [comment]
Q for @bcantrill  in the CR.

**Comment by trentm** [comment]
Added a 'v1.0.0' tag and published manta-thoth@1.0.0 to npm.
